"""MEMORY — events become objects in the world, and then they fade.

Pietro: "Do they have events generated by us that become objects in
their world with a persistent memory that fades over time?"

Yes, and this is where they live.

An event here is not a delta applied once and discarded. It is an
OBJECT with a life of its own: it happened somewhere, on a day, to
particular people, and it stays in the world afterwards. Its salience
decays on a half-life, so it fades from the front of everyone's mind
without ever quite leaving — which is how collective memory actually
behaves. A war twenty years gone still moves a population, faintly.

Two properties make this more than a decay curve:

  REHEARSAL. An event that keeps being referenced does not fade. Every
  time something similar happens, the older memory is refreshed, which
  is why a society that keeps getting hit by the same thing develops a
  permanent sensitivity to it while a one-off eventually becomes
  history.

  LOCALITY. A memory belongs to the people it happened to and spreads
  from them along the social fabric. A famine in one region is a
  searing memory there and a fact somewhere else.

Anyone can put an event into this world — the news pipeline, a
scenario, or a person asking "what if". Once inside, it obeys the same
rules as everything else that happened.
"""
from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

DEFAULT_HALF_LIFE = 720.0      # days for salience to halve
REHEARSAL_BOOST = 0.35         # how much a similar event refreshes an old one
FORGOTTEN = 0.02               # below this, an event leaves the world


@dataclass
class Memory:
    """One thing that happened, and is still happening to people."""
    id: str
    label: str
    day: float
    force_signature: np.ndarray     # (8,) what it did
    scope: np.ndarray               # bool per agent: who it happened to
    salience: float = 1.0
    half_life: float = DEFAULT_HALF_LIFE
    rehearsals: int = 0
    origin: str = "world"           # world | news | scenario | question


@dataclass
class Chronicle:
    """Everything this civilisation remembers."""
    events: list = field(default_factory=list)
    forgotten: int = 0
    total_ever: int = 0

    def remember(self, m: Memory) -> None:
        # REHEARSAL: does this resemble something already remembered?
        for old in self.events:
            sim = float(np.dot(old.force_signature, m.force_signature))
            denom = (np.linalg.norm(old.force_signature)
                     * np.linalg.norm(m.force_signature))
            if denom > 0 and sim / denom > 0.80:
                old.salience = min(1.0, old.salience + REHEARSAL_BOOST)
                old.rehearsals += 1
        self.events.append(m)
        self.total_ever += 1

    def tick(self, civ, dt_days: float = 1.0) -> dict:
        """Time passes. Memories fade, and while they last they press."""
        keep, pressed = [], 0
        for m in self.events:
            m.salience *= 0.5 ** (dt_days / m.half_life)
            if m.salience < FORGOTTEN:
                self.forgotten += 1
                continue
            # a living memory keeps acting on the people who hold it
            if m.scope is not None and m.scope.any():
                civ.forces[m.scope] = np.clip(
                    civ.forces[m.scope]
                    + m.salience * m.force_signature[None, :] * 0.02
                    * dt_days, 0.0, 1.0)
                pressed += int(m.scope.sum())
            keep.append(m)
        self.events = keep
        return {"remembered": len(self.events),
                "forgotten_total": self.forgotten,
                "people_under_memory": pressed,
                "oldest_days": (round(max((0.0,) + tuple(
                    m.salience for m in self.events)), 4)
                    if self.events else 0.0)}

    def spread(self, civ, rng: np.random.Generator,
               rate: float = 0.06) -> int:
        """Memories travel to the people who know the people it happened to.

        `rng` is the world's stream, not the global one. This used to
        call `np.random.random`, which ignores every seed the caller
        sets: any run with a non-empty chronicle was unreproducible, and
        paired branches were not on the same dice even though branch.py
        hands both arms an identical generator. The sampling law is
        unchanged — same rate, same exposure, same distribution — only
        the source of the draws.
        """
        moved = 0
        deg = np.maximum(np.asarray(civ.adj.sum(axis=1)).ravel(), 1.0)
        for m in self.events:
            if m.scope is None or not m.scope.any():
                continue
            exposure = np.asarray(civ.adj @ m.scope.astype(np.float64)
                                  ).ravel() / deg
            catch = (~m.scope) & (rng.random(civ.n) < rate * exposure)
            if catch.any():
                m.scope = m.scope | catch
                moved += int(catch.sum())
        return moved


def event_from_news(headline: str, tone: float, day: float,
                    scope: np.ndarray, origin: str = "news") -> Memory:
    """A real headline becomes a thing that happened in this world."""
    from earth1.types import Force
    sig = np.zeros(len(Force))
    sig[Force.FEAR] = max(0.0, -tone) * 0.5
    sig[Force.COLLECTIVE] = abs(tone) * 0.2
    sig[Force.EXPERIENCE] = 0.15
    return Memory(id=f"news:{abs(hash(headline)) % 10**9}",
                  label=headline[:120], day=day, force_signature=sig,
                  scope=scope, origin=origin)
